@echo off

SET password=

REM remove stored cookie file if its older than 7 days
forfiles -p "z:" -s -m cookies_yt.txt -d 7 -c "cmd /c del @path" 2>NUL

REM make cookie file if its missing
if not exist z:\cookies_yt.txt (   
	REM extract all cookies from browser 
	yt-dlp --cookies-from-browser chrome --cookies z:\cookies.txt 2>NUL

	REM keep only youtube cookies, seems to work fine like this, and id prefer 
	REM not to have *all* my cookies just lying around.
	echo # Netscape HTTP Cookie File > z:\cookies_yt.txt
	echo # This file is generated by yt-dlp.  Do not edit. >> z:\cookies_yt.txt
	REM echo: for newline
	echo: >> z:\cookies_yt.txt
	grep -i youtube z:\cookies.txt >> z:\cookies_yt.txt 
	
	REM clean up file with all cookies
	rm z:\cookies.txt
)

REM literal % needs to be escaped as %%
REM %* passes all arguments
plink -batch -ssh jordan@192.168.10.10 -pw %password% "yt-dlp -N 5 -S vcodec:h264,res:1080,ext:mp4:m4a -o '/storage/YouTube/%%(channel)s - %%(title)s [%%(id)s].%%(ext)s' --merge-output-format mp4 --embed-chapters --embed-subs --no-mtime --cookies /storage/YouTube/cookies_yt.txt --mark-watched --no-playlist %*"

pause